name: Terraform Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Terraform Init
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.3

    - name: Terraform Plan
      uses: hashicorp/terraform-github-actions@v0.2.0
      with:
        args: plan

    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions@v0.2.0
      with:
        args: apply
      env:
        TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
